global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# rule_files: add later
#   - /etc/prometheus/rules/*.yml
#   - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3000"]   # <-- your backend port here